/** Dutch editorial content for the existing regional and sightseeing pages. */
export const dutchLocations: Record<string, {intro: string; highlights: string[]}> = {
  'taxi-klotten': {intro:'Klotten ligt enkele minuten stroomafwaarts van Cochem, direct aan de B49. Veel ritten gaan naar het Wild- und Freizeitpark Klotten of naar de wijnhuizen in het dorp.',highlights:['Wild- und Freizeitpark Klotten voor gezinnen','Wijnhuizen en wijnlokalen in het centrum','Vervoer naar station Cochem','Startpunten voor wandelingen bij de Brauselay']},
  'taxi-valwig': {intro:'Valwig ligt aan de overkant van de Moezel, op enkele kilometers van Cochem. Het wijndorp staat bekend om de steile wijngaarden en wijnlokalen. Na een wijnproeverij kunt u telefonisch een taxi aanvragen.',highlights:['Wijnhuizen en wijnproeverijen','Vervoer naar Cochem','Wandelroutes door de wijngaarden','Ophalen bij uw accommodatie']},
  'taxi-valwigerberg': {intro:'Valwigerberg ligt op het plateau boven het Moezeldal. De weg omhoog heeft meerdere haarspeldbochten, waardoor de reistijd langer kan zijn dan de afstand doet vermoeden. Een taxi is handig voor wandelaars en gasten van de vakantieboerderijen.',highlights:['Vakantieboerderijen op het plateau','Vervoer voor wandelaars','Aansluiting naar station Cochem','Geef het exacte ophaaladres door']},
  'taxi-bruttig-fankel': {intro:'Bruttig-Fankel bestaat uit twee dorpsdelen aan de Moezel, met vakwerkhuizen en wijnhuizen. Geef bij uw telefoontje aan of u in Bruttig of Fankel wilt worden opgehaald. Veel ritten gaan naar Cochem of het station.',highlights:['Ophalen in Bruttig en Fankel','Wijnhuizen en historisch dorpscentrum','Avondritten naar Cochem','Vervoer naar het station']},
  'taxi-ernst': {intro:'Ernst is een wijndorp tussen Cochem en Bruttig, direct aan de Moezel. De korte rit volgt de oeverweg. Een taxi is handig voor een bezoek aan de wijnhuizen of voor aansluiting op de trein in Cochem richting Koblenz of Trier.',highlights:['Wijnhuizen aan de Moezel','Korte rit naar Cochem','Vervoer naar station Cochem','Ophalen bij hotels en pensions']},
  'taxi-beilstein': {intro:'Beilstein wordt het Doornroosje van de Moezel genoemd. Het middeleeuwse centrum en de ruïne van Burg Metternich trekken veel bezoekers. Parkeerplaatsen zijn beperkt; vanaf de dorpsingang bereikt u het centrum te voet.',highlights:['Middeleeuws dorpscentrum','Burg Metternich','Uitstappen bij de dorpsingang','Spreek de terugrit vooraf af']},
  'taxi-landkern': {intro:'Landkern ligt op het plateau tussen Cochem en Kaisersesch, buiten het Moezeldal. Vooral in het weekend zijn de busverbindingen beperkt. Een taxi biedt vervoer naar Cochem en de omliggende plaatsen.',highlights:['Vervoer vanaf het plateau','Ritten naar Cochem en Kaisersesch','Ophalen bij uw accommodatie','Vraag tijdig naar beschikbaarheid']},
  'taxi-faid': {intro:'Faid ligt op het plateau ten westen van Cochem en is bereikbaar via de bochtige weg omhoog. Het dorp biedt vakantieverblijven en startpunten voor wandelingen. U kunt een taxi aanvragen voor het station of de terugrit in de avond.',highlights:['Vakantieverblijven in Faid','Startpunten voor wandelingen','Vervoer naar station Cochem','Avondritten op telefonische aanvraag']},
  'taxi-treis-karden': {intro:'Treis-Karden ligt stroomafwaarts richting Koblenz. Treis en Karden liggen aan verschillende kanten van de Moezel. De plaats staat bekend om de St. Castorkerk en als uitvalsbasis voor Burg Eltz. Geef uw dorpsdeel of station als vertrekpunt door.',highlights:['Ophalen in Treis en Karden','Station Treis-Karden','St. Castorkerk','Uitvalsbasis voor Burg Eltz']},
  'taxi-ediger-eller': {intro:'Ediger-Eller heeft een historisch dorpscentrum met smalle straten. Het station ligt buiten het centrum, waardoor een taxi handig is voor de laatste kilometers naar uw accommodatie. Ook de wijngaarden van de Calmont liggen in de omgeving.',highlights:['Historisch centrum van Ediger','Station Ediger-Eller','Wandelingen bij de Calmont','Geef aan of u in Ediger of Eller verblijft']},
  'taxi-senheim': {intro:'Senheim ligt in een Moezelbocht tussen Cochem en Zell. Een brug verbindt het dorp met Senhals. Wijnbouw en fietstoerisme spelen hier een belangrijke rol. Vraag eventueel fietsvervoer vooraf telefonisch aan.',highlights:['Ophalen in Senheim en Senhals','Moezelfietsroute','Wijnhuizen en vakantieverblijven','Fietsvervoer alleen op voorafgaand verzoek']},
  'taxi-bremm': {intro:'Bremm ligt aan de voet van de Calmont en trekt bezoekers voor de wandelroute en het uitzicht op de Moezelbocht. Met een taxi kunt u naar het startpunt rijden en bij het eindpunt worden opgehaald. Spreek dit vooraf af.',highlights:['Calmont en de Moezelbocht','Vervoer naar het wandelstartpunt','Ophalen bij het eindpunt','Spreek ophaaltijd en locatie vooraf af']},
  'taxi-briedern': {intro:'Briedern ligt tussen Senheim en Beilstein aan een rustige Moezelbocht. Het dorp is populair bij fietsers en wandelaars en heeft beperkte busverbindingen. Een taxi naar Cochem of het station kan daarom handig zijn.',highlights:['Rustig dorp aan de Moezel','Vervoer voor wandelaars en fietsers','Ritten naar Cochem','Aansluiting op de trein']},
  'taxi-kaisersesch': {intro:'Kaisersesch ligt in de Eifel boven het Moezeldal en is het eindpunt van de spoorlijn vanuit Andernach. Een taxi verbindt het station met Cochem en de Moezeldorpen. Ook ritten naar de aansluiting op de A48 zijn mogelijk op aanvraag.',highlights:['Station Kaisersesch','Vervoer naar Cochem en de Moezel','Aansluiting op de A48','Vraag langere ritten vooraf aan']},
  'taxi-ulmen': {intro:'Ulmen ligt in de Vulkaaneifel en is bekend om het Ulmener Maar en de kasteelruïne. De rit vanuit Cochem gaat over de hoogten van de Eifel. U kunt telefonisch vervoer naar vakantieverblijven of de A48 aanvragen.',highlights:['Ulmener Maar','Kasteelruïne van Ulmen','Vakantieverblijven in de Vulkaaneifel','Vervoer naar de A48']},
  'taxi-zell-mosel': {intro:'Zell aan de Moezel is bekend om de wijn Zeller Schwarze Katz. Het ligt ongeveer 30 kilometer stroomopwaarts van Cochem. De rit langs de rivier duurt ongeveer 35 minuten. Vraag vervoer naar een wijnproeverij, feest of hotel telefonisch aan.',highlights:['Wijngebied Zeller Schwarze Katz','Rit langs de Moezel','Vervoer naar hotels en wijnhuizen','Plan ritten tijdens feesten ruim van tevoren']},
};
export const dutchRoutes: Record<string, {destination:string; intro:string; highlights:string[]; faq:{question:string;answer:string}[]}> = {
  'burg-eltz': {destination:'Burg Eltz',intro:'Burg Eltz ligt verscholen in het bos en is vanuit Cochem lastig met het openbaar vervoer te bereiken. Met een taxi rijdt u naar de bezoekersparkeerplaats bij de Antoniuskapelle. Vanaf daar gaat u te voet verder of gebruikt u de pendelbus wanneer deze rijdt.',highlights:['Rechtstreeks naar de bezoekersparkeerplaats','Geen overstappen onderweg','Spreek een lokale terugrit telefonisch af','Mogelijke tussenstop in Treis-Karden of Moselkern op aanvraag'],faq:[{question:'Waar zet de taxi ons af bij Burg Eltz?',answer:'Bij de bezoekersparkeerplaats aan de Antoniuskapelle. Vanaf daar loopt u naar de burcht of neemt u de pendelbus wanneer deze beschikbaar is. Controleer de actuele bezoekersinformatie bij de burcht.'},{question:'Kunnen we na ons bezoek worden opgehaald?',answer:'Vraag de lokale terugrit vooraf telefonisch aan. Spreek tijd en ontmoetingsplaats af; het mobiele bereik in het dal is niet overal goed.'}]},
  'flughafen-hahn': {destination:'Luchthaven Frankfurt-Hahn',intro:'Luchthaven Frankfurt-Hahn ligt in de Hunsrück, ongeveer 40 kilometer van Cochem. Deze transfer vertrekt uitsluitend vanuit Cochem en brengt u naar het terminalgebouw. Bel vooraf om beschikbaarheid, vertrektijd en prijs te bespreken.',highlights:['Ophalen bij uw adres in Cochem','Rechtstreeks naar het terminalgebouw','Geef passagiers en bagage vooraf door','Alleen vanuit Cochem naar de luchthaven'],faq:[{question:'Hoe vroeg moet ik mijn rit naar Hahn aanvragen?',answer:'Bel zo vroeg mogelijk, vooral voor vroege vluchten. Houd naast de geschatte reistijd voldoende tijd aan voor inchecken en veiligheidscontrole.'},{question:'Halen jullie ook reizigers op op de luchthaven?',answer:'Nee. De aangeboden luchthaventransfers vertrekken uitsluitend vanuit Cochem. Deze website biedt geen vervoer vanaf de luchthaven naar Cochem.'}]},
  'koblenz': {destination:'Koblenz',intro:'Koblenz ligt ongeveer 55 kilometer stroomafwaarts van Cochem, waar de Moezel en Rijn samenkomen bij het Deutsches Eck. Een taxi kan handig zijn buiten treintijden of wanneer u veel bagage heeft. Geef het station of uw exacte bestemming telefonisch door.',highlights:['Naar station Koblenz of de binnenstad','Handig bij vroege treinverbindingen','Lokale terugritten na evenementen op aanvraag','Ophalen bij uw adres in Cochem'],faq:[{question:'Wanneer is een taxi naar Koblenz handig?',answer:'Bijvoorbeeld buiten de dienstregeling van de trein, bij veel bagage of als u rechtstreeks naar een adres wilt reizen. Vergelijk de richtprijs en vraag beschikbaarheid telefonisch na.'}]},
  'trier': {destination:'Trier',intro:'Trier ligt ongeveer 90 kilometer stroomopwaarts van Cochem. De rit duurt ongeveer 75 minuten, afhankelijk van de route en het verkeer. Geef telefonisch door of u naar de Porta Nigra, het station of uw hotel wilt reizen.',highlights:['Porta Nigra, Kaiserthermen en de Dom','Route via de A1 of langs de Moezel','Dagtocht met lokale terugrit op aanvraag','Geef de groepsgrootte vooraf door'],faq:[{question:'Is een dagtocht naar Trier met terugrit mogelijk?',answer:'Vraag beide ritten vooraf telefonisch aan. Spreek bestemming en ophaaltijd af, zodat de beschikbaarheid voor beide ritten kan worden bevestigd.'}]},
};
export const dutchAttractions: Record<string, {name:string; description:string; secretTip:string; taxiNote?:string}> = {
 'reichsburg-cochem': {name:'Reichsburg Cochem',description:'De burcht werd voor het eerst vermeld in 1051. Koning Konrad III maakte er in 1151 een rijksburcht van. Franse troepen namen de burcht in 1688 in en verwoestten haar in 1689. De Berlijnse koopman Louis Fréderic Jacques Ravené liet haar tussen 1868 en 1877 in neogotische stijl herbouwen.',secretTip:'Het interieur is alleen met een rondleiding te bezoeken. De wandeling omhoog is kort maar steil. Kom vroeg in de ochtend en controleer vooraf de mogelijkheden voor een rondleiding.',taxiNote:'Vraag telefonisch naar vervoer tot de parkeerplaats bij de burcht.'},
 'bundesbankbunker': {name:'Bundesbankbunker Cochem',description:'De Deutsche Bundesbank bouwde tussen 1962 en 1964 een bunker in Cond, ongeveer 30 meter onder de grond. Van 1964 tot 1988 lag hier tot 15 miljard mark aan geheime noodvaluta, de BBk II. Sinds maart 2016 is de bunker toegankelijk voor rondleidingen.',secretTip:'De ingang ligt onder een onopvallend gebouw. U kunt alleen met een rondleiding naar binnen. Neem ook in de zomer een jas mee voor het ondergrondse bezoek.'},
 'sesselbahn-pinnerkreuz': {name:'Stoeltjeslift naar het Pinnerkreuz',description:'De stoeltjeslift van Cochem brengt bezoekers in open tweepersoonscabines naar het Pinnerkreuz. Vanaf het bergstation volgt u een rotsachtig pad met enkele treden en leuningen naar het uitzichtpunt. U moet stevig ter been zijn.',secretTip:'Ga met de lift omhoog en wandel door de wijngaarden terug. De afdaling duurt ongeveer een halfuur en biedt mooie uitzichten op de burcht.'},
 'historische-senfmuehle': {name:'Historische mosterdmolen',description:'In de historische mosterdmolen van Cochem wordt al meer dan 200 jaar mosterd gemaakt volgens een traditioneel proces. De molen is vanuit de stad te voet bereikbaar.',secretTip:'Een geschikte bestemming op een regenachtige dag: het bezoek vindt binnen plaats. Mosterd is bovendien een praktisch souvenir.'},
 'burg-eltz': {name:'Burg Eltz',description:'Burg Eltz ligt in de bossen van het Eltzdal. Met de auto rijdt u via Münstermaifeld naar de parkeerplaats bij de Antoniuskapelle. Daarna is het ongeveer 800 meter lopen, of u neemt de seizoensgebonden pendelbus. Vanuit Moselkern loopt een wandelroute van ongeveer 4,5 kilometer langs de Elzbach naar de burcht.',secretTip:'Op de route vanuit Moselkern verschijnt de burcht plotseling achter een bocht in het bos. U kunt naar Moselkern reizen, omhoog wandelen en een lokale taxi bij de bezoekersparkeerplaats afspreken.',taxiNote:'Vraag telefonisch een rit vanuit Cochem naar de bezoekersparkeerplaats aan.'},
 'calmont': {name:'Calmont bij Bremm',description:'De Calmont tussen Eller en Bremm geldt als de steilste wijngaard van Europa. De helling is ongeveer 380 meter hoog en bereikt circa 65 graden. Een route van ongeveer vijf kilometer bevat klimgedeelten met staalkabels, beugels en ladders. Stevig schoeisel, geen hoogtevrees en een vaste tred zijn noodzakelijk.',secretTip:'Loop de route in één richting en spreek vervoer bij het eindpunt af. Het mobiele bereik is onbetrouwbaar: regel tijd en ontmoetingsplaats vooraf.',taxiNote:'Vervoer naar het startpunt en ophalen bij het eindpunt op telefonische aanvraag.'},
 'beilstein': {name:'Beilstein',description:'Beilstein wordt het Doornroosje van de Moezel genoemd. Het middeleeuwse centrum heeft smalle straatjes en vakwerkhuizen. De ruïne van Burg Metternich ligt erboven. Het dorp is klein en kan in het seizoen druk zijn.',secretTip:'Parkeerplaatsen aan de dorpsrand raken snel vol. Een bezoek zonder eigen auto kan prettig zijn. In de late middag is het vaak rustiger.'},
 'moselpromenade': {name:'Moezelpromenade en uitzicht vanuit Cond',description:'De promenade volgt de Moezeloever door Cochem met uitzicht op de wijngaarden en de Reichsburg. Aan de overkant ligt Cond, waar u de burcht en oude binnenstad samen kunt zien.',secretTip:'Voor een klassieke foto van Cochem gaat u naar Cond. Van daaruit passen de burcht, brug en oude stad in één beeld. Probeer het in de vroege avond.'},
 'heimat-und-weinfest': {name:'Heimat- und Weinfest',description:'Het Heimat- und Weinfest is het grootste feest van Cochem. In 2026 vond het plaats van 27 tot en met 31 augustus. Wijnboeren schenken wijn op de markt en langs de promenade. Tot de hoogtepunten behoren de optocht op zondag en het vuurwerk in de avond.',secretTip:'Tijdens het feest is het druk. Vraag een lokale terugrit naar uw accommodatie vooraf telefonisch aan en controleer voor een volgend bezoek de actuele feestdata.',taxiNote:'Vraag ritten op feestdagen ruim van tevoren aan.'},
};
